### ISSUE TITLE
can we improve the efficiency of getStats?

### ISSUE THREAD

**Issue by tombisho** [lifecycle-project/ds-helper#25]
I really like the `getStats` function. I do have a concern that if you have many cohorts distributed over the world, then the large number of transactions with the server might make it a bit slow. I was wondering about a couple of changes:

1. The calls to ds.summary are done one by one (to avoid the problem of a variable being missing in a cohort). I was trying to think of a way to remove the problem cohorts and call to the remaining cohorts in one go to get the parallelisation.
2. In general the calls to the server side could be made directly rather than through the `dsBaseClient` functions as these often repeat checks already done (for example, many calls to `exists`). This can be done using `datashield.aggregate()`

**Comment by tombisho** [comment]
:( I spent a few hours removing the per cohort calls to `ds.summary()` and replacing it with a single call to all cohorts at once....only to find that `ds.summary()` itself then does per cohort calls

So I think these improvements may be prevented by `ds.summary()`

**Comment by timcadman** [comment]
Agh that's annoying! I agree in principle it should be possible to make it much more efficient. Maybe worth having a zoom call with Sido and demetris/stuart to discuss?

**Comment by tombisho** [comment]
I could open an issue on the DS Github prior to a discussion, because actually the native ds.summary function is the source of the challenge!

**Comment by timcadman** [comment]
Ok I've completely rewritten this, minimising ds calls and also calling the serverside functions directly. It is now over twice as quick!
